server:
  port: 10010   # 网关端口
spring:
  application:
    name: gateway   # 服务名称
  cloud:
    nacos:
      server-addr: 121.199.48.201:8848   # nacos 地址
    gateway:
      routes:   # 网关路由配置
        - id: user-service # 路由 id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http 就是固定地址
          uri: lb://userservice   # 路由的目标地址 lb 就是负载均衡，后面跟服务名称
          predicates:   # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/**   # 这个是按照路径匹配，只要以 /user/ 开头就符合要求
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**